Hello microverse
fatima-najafi/Hello-World pull request #4
Opened 2023-04-26 18:31 UTC by fatima-najafi

Remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
Create a new GitHub repo.
Create a new branch according to the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) rules.
Add a .gitignore file.
Add node_modules to gitignore file.
Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
Add 3 files (each one in a separate commit):
A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
A .css file that includes one class with styles for your header (make it in your favorite color).
A test.md file with the text "This file should be ignored by git".
Make sure that the last file is actually ignored by git and is not present in your GitHub repository.
Open a pull request.

2023-04-27 09:35 UTC, aamirkhan2478 requested changes
Hi @fatima-najafi , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 09:35 UTC, aamirkhan2478 commented on README.md
- [ ] Please don't remove all data from the `README` file the only `FAQ` section is optional. Other sections are mandatory please add all the following sections with your customise data :slightly_smiling_face: 

- Table of Contents
- Your Project name
- Built with
- Tech Stack (`In the tech stack section remove server and database details and in client details, you just add 'HTML and CSS' instead of 'reactjs'`)
- Key Features
- Live demo (`Remove the link and just write 'coming soon' instead of link`)
- Get started
- Authors
- Future Features
- Contributing
- Acknowledgments
- License (`Make sure your licence link is working`)

- [ ] Please add again [README](https://github.com/microverseinc/readme-template) template as I mentioned above :point_up_2: section don't remove these sections and remember you can customize all the sections also remove the microverse logo :+1: 

- [ ] Also remove the following lines from your update README file because these lines are only for you not for others :slightly_smiling_face: 

![Screenshot from 2023-04-27 14-32-23](https://user-images.githubusercontent.com/45226848/234822522-85041c44-6cf5-4b05-8f3b-1df7f7bda635.png)

2023-04-27 09:35 UTC, aamirkhan2478 commented on test.md
- [ ] As mentioned by the previous reviewer #2 :point_left: make sure that the `test.md` file is actually ignored by git and is not present in your GitHub repository but this file is still in your GitHub repository. So kindly fix this issue :+1:

2023-04-27 09:35 UTC, aamirkhan2478 commented on MIT.md
> +###### APP TYPE can be a webpage/website, a web app, a software and so on
[OPTIONAL] Kindly remove these two lines because these lines only for you not for others :+1:

2023-04-28 08:21 UTC, christianbiring1 approved these changes
Hi @fatima-najafi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 14:33 UTC, merged